---
driver:
  name: docker
  binary: docker 2>/dev/null
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    attributes:
